config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'annotations#index'
  resources :annotations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/annotation.rb
class Annotation < ApplicationRecord

  enum priority: { alto: 0, medio: 1, baixo: 2}
  scope :like_value, -> (title) { where('title LIKE ? or body LIKE ?', "%#{title}%", "%#{title}%") }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController

  before_action :authenticate_user!

  def index
    annotations = Annotation.all
    annotations = Annotation.like_value(params[:by_annotation]) if params[:by_annotation].present?
    @annotations = annotations.paginate(page: params[:page], per_page: 5)
  end

  def show
    @annotation = Annotation.find(params[:id])
  end

  def new
    @annotation = Annotation.new
  end

  def create
    ap = annotation_params
    ap[:priority] = ap[:priority].to_i
    @annotation = Annotation.new(ap)
    if @annotation.save
      redirect_to root_path, notice: 'Anotação criada com sucesso!'
    else
      redirect_to :new
    end
  end

  def edit
    @annotation = Annotation.find(params[:id])
  end

  def update
    ap = annotation_params
    ap[:priority] = ap[:priority].to_i
    @annotation = Annotation.find(params[:id])
    if @annotation.update(ap)
      redirect_to root_path
    else
      redirect_to :edit
    end
  end

  def destroy
    @annotation = Annotation.find(params[:id])
    @annotation.destroy
    redirect_to root_path, notice: 'Anotação deletado com sucesso!'
  end

  private

  def annotation_params
    params.require(:annotation).permit(:title, :body, :date, :priority)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annotations/_form.html.erb
<div class="container">
  <%= form_with model: @annotation do |form| %>
    <div class="form-group mb-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control", autofocus: true %>
      <% @annotation.errors.full_messages_for(:title).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :body %>
      <%= form.text_area :body, class: "form-control", autofocus: true %>
      <% @annotation.errors.full_messages_for(:body).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :date %>
      <%= form.date_field :date, class: "form-control", autofocus: true %>
      <% @annotation.errors.full_messages_for(:date).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :priority %><br />
      <%= form.select(:priority, options_for_select([['Alto', 0], ['Medio', 1], ['Baixo', 2]]), { prompt: 'Selecione'}, 
      { class: "form-control", autofocus: true })%>
    </div>

    <%= form.submit "Anotar", class: "btn btn-light" %>
    <%= link_to('Voltar', annotations_path, class: 'btn btn-light') %>
  <% end %>
</div>

app/views/annotations/edit.html.erb
<h3 class="text-center">Editar anotação:</h3>
<hr/>
<%= render "form" %>

app/views/annotations/index.html.erb
<h3 class="text-center">Suas anotações</h3>
<hr/>

<br clear="all">
<div class="card bg-light mt-2 mb-4">
	<div class="card-body">
		<h5>Filtro:</h5>
		<%= form_with url: annotations_url, method: :get do |form| %>
		  <div class="form-group mb-3">
		    <%= form.label :annotation %>
		    <%= form.text_field :by_annotation, value: params[:by_annotation], class: "form-control", autofocus: true %>
		  </div>
		  <%= form.submit 'Buscar', class: "btn btn-light" %>
		<% end %>
	</div>
</div>

<%= link_to('Criar anotação', new_annotation_path, class: 'btn btn-light float-end') %>

<% if @annotations.nil? %>
	<div class="alert alert-info">
		Nenhuma anotação adicionada
	</div>
<% else %>
	<table class="table">
		<thead>
			<tr>
				<th>Título:</th>
				<th>Texto:</th>
				<th>Data:</th>
				<th>Prioridade:</th>
				<th>#</th>
			</tr>
		</thead>
		<tbody>
			<% @annotations.order("created_at desc").each do |annotation| %>
				<tr>
					<td><%= annotation.title %></td>
					<td><%= annotation.body %></td>
					<td><%= annotation.date %></td>
					<td><%= annotation.priority %></td>
					<td>
						<div class="dropdown">
          					<span class="navbar-text">
					    	<button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
											    Opções
							  </button>
							  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
							  	<li><%= link_to('Visualizar', annotation_path(annotation.id), class: 'dropdown-item') %></li>
							    <li><%= link_to('Editar', edit_annotation_path(annotation.id), class: 'dropdown-item')%></li>
							    <li><hr class="dropdown-divider"></li>
							    <li><%= button_to('Deletar', annotation_path(annotation), method: :delete, class: 'dropdown-item', data: {confirm: 'Tem certeza?'}) %></li>
							  </ul>
							</span>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<%= will_paginate @products, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination page-item justify-content-center' %>

app/views/annotations/new.html.erb
<h3 class="text-center">Nova anotação:</h3>
<hr/>

<%= render "form" %>

app/views/annotations/show.html.erb
<h3>
	<%= @annotation.title %> <br/>
</h3>

<hr/>

<h5>Título: <%= @annotation.title %></h5>
<h5>Texto: <%= @annotation.body %></h5>
<h5>Data: <%= @annotation.date %></h5>
<h5>Prioridade: <%= @annotation.priority %></h5>

<%= link_to('Voltar', annotations_path, class: 'btn btn-light') %>
<%= link_to('Editar', edit_annotation_path, class: 'btn btn-light') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAnnotations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container mt-3">
    <% if current_user %>
      <%= link_to('Sair', destroy_user_session_path, method: :delete, class: 'btn btn-light float-end') %>
    <% end %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key == 'alert' ? 'danger' : 'info' %>">
        <%= value %>
      </div>
    <% end %>
      <%= yield %>   
  </body>
</html>